### ISSUE TITLE
type 6으로 고쳐주세요

### ISSUE THREAD

**Issue by injoon5** [kiki7000/discord.py-buttons#1]
이 라이브러리를 쓰다가 계속 상호작용 오류가 나서 찾아보니 koreanbots에서 버튼 콜백할때 type 6으로 하면 된다고 해서 혼자서 고쳐서 PR을 넣으려고 했으나, 제 실력이 너무 딸려서 고치지 못하고 이렇게 issue를 남깁니다.

**Comment by kiki7000** [comment]
알겠습니다!

**Comment by injoon5** [comment]
해결 되었으니 닫겠습니다.
